### ISSUE TITLE
month names instead of week numbers

### ISSUE THREAD

**Issue by cperk** [RetoSchmucki/rbms#15]
Would it be possible to add the option of plotting month names rather than week numbers on x axis?

https://retoschmucki.github.io/rbms/articles/Get_Started_1.html

**Comment by RetoSchmucki** [comment]
Good idea! I will add the option and let you know once implemented 👍

**Comment by RetoSchmucki** [comment]
Month name is now implemented; see the example on the website [https://retoschmucki.github.io/rbms/](https://retoschmucki.github.io/rbms/)
```R
# for multiple year curves overlapping on a base year, use the argument BaseYear
plot(ts_flight_curve, year = 2000, SiteID = 1, col = 'dodgerblue4')
points(ts_flight_curve, year = 2002, SiteID = 1, BaseYear = 2000, type = 'l', col = 'cyan4')
points(ts_flight_curve, year = 2001, SiteID = 1, BaseYear = 2000, type = 'l', col = 'orange')
legend("topright", legend = c("2000", "2001", "2002"), 
   col = c("dodgerblue4", "cyan4", "orange"), lty = 1,
   box.lty=0)
```
