### ISSUE TITLE
Weird collated index and lower IC

### ISSUE THREAD

**Issue by SarahVray** [RetoSchmucki/rbms#20]
Hi @RetoSchmucki, that's me again ^^"
For several species in some years, I obtain a very low collated index and/or a very low CI. 
- The low collated indices always correspond to a year with 0 specimen recorded, so maybe this very low value is normal? 
- The low CIs always correspond to years with very few occurrences, not enough to build a flight curve, but I am wondering why the lower CI is so low whereas the upper CI looks normal?

Here is the example of A. agestis:
![Aricia agestis_collated index](https://github.com/RetoSchmucki/rbms/assets/110041178/f32914e6-95ae-411d-834c-06357a2eed97)
[Aricia agestis_collated index.csv](https://github.com/RetoSchmucki/rbms/files/12588245/Aricia.agestis_collated.index.csv)
Here are the counts per year:
![Aricia agestis_weighted_counts_per_year_month](https://github.com/RetoSchmucki/rbms/assets/110041178/6f53d891-b549-4b1e-b638-0a803383400b)
![Aricia agestis_flight curve](https://github.com/RetoSchmucki/rbms/assets/110041178/20b21321-13ee-483f-93dc-277c1657eca9)

Here is another example, P. c-album:
[Polygonia c-album_collated index.csv](https://github.com/RetoSchmucki/rbms/files/12588130/Polygonia.c-album_collated.index.csv)
![Polygonia c-album_collated index](https://github.com/RetoSchmucki/rbms/assets/110041178/d8f0ed75-3aab-44a1-973d-5320046c3fbd)
In 2012, the collated index looks OK but the lower CI is very low. 
In 2017, the collated index is very low although it is the year with the highest counts:
![Polygonia c-album_weighted_counts_per_year_month](https://github.com/RetoSchmucki/rbms/assets/110041178/bb86bfde-37d5-4226-a01f-de0f517437c0)
But there is clearly an issue with the computed flight curve for 2017 (see issue #21).

Thank you very much for your help!

**Comment by RetoSchmucki** [comment]
Hi @SarahVray 
The CI is computed by resampling your sites. If you have a species that is only present in very few sites, there is a chance that the resampling (with replacement) might not include the site where it is observed, resulting in a collated index of "0". If this happens more than 5% of the time, the "0" will be in your 95%CI. Unfortunately, this is the limit of the bootstrap CI, and it does not perform well with species on rare sites.

**Comment by SarahVray** [comment]
Hi @RetoSchmucki,
Yes I see, it makes sense, thank you for your explanation! And what about the very low collated index? Is it simply because 0 specimen was recorded during this year ?

**Comment by SarahVray** [comment]
Hi @RetoSchmucki,
I see, it makes sense. Thank you for your explanation!
